# Infinite Talk ComfyUI Worker Configuration

# ComfyUI 环境配置
comfyui:
  # 自动检测的环境模式: existing_volume 或 container_default
  environment_mode: auto
  # ComfyUI 路径（自动检测）
  path: auto
  # 虚拟环境路径（自动检测）
  venv_path: auto
  # 监听端口
  port: 8188
  # 日志级别
  log_level: INFO

# Infinite Talk 工作流配置
infinite_talk:
  # 工作流模板文件
  workflow_template: workflow_infinite_talk.json
  # 模型路径配置
  models:
    base_path: /workspace/ComfyUI/models
    checkpoints: checkpoints/
    loras: loras/
    embeddings: embeddings/
    vae: vae/
    # Infinite Talk 特定模型
    infinite_talk_models: infinite_talk/
    audio_models: audio/
    voice_models: voice/

  # 默认参数
  defaults:
    text_input_node: "text_input"
    voice_type_node: "voice_selector"
    output_node: "audio_output"
    default_voice: "female"
    supported_voices:
      - "male"
      - "female"
      - "child"
      - "robot"

# API 配置
api:
  # RunPod 配置
  runpod:
    serve_locally: true
    api_host: 0.0.0.0
    api_port: 8000

  # 请求配置
  request:
    # 超时时间（秒）
    timeout: 300
    # 重试次数
    retries: 3
    # 重试间隔（秒）
    retry_delay: 5

# 资源配置
resources:
  # GPU 配置
  gpu:
    enabled: true
    memory_limit: null  # null 表示无限制

  # 内存配置
  memory:
    # 清理临时文件
    cleanup_temp: true
    # 缓存清理间隔（秒）
    cleanup_interval: 3600

# 调试配置
debug:
  # 启用详细日志
  verbose_logging: true
  # 保存调试信息
  save_debug_info: false
  # 调试输出路径
  debug_output_path: /workspace/debug/

# 监控配置
monitoring:
  # 启用健康检查
  health_check: true
  # 健康检查间隔（秒）
  health_check_interval: 30
  # 启用性能监控
  performance_monitoring: false
